---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: delete all resources
      import_role:
        name: example-cnf-destroy
    - name: create catalog
      import_role:
        name: example-cnf-catalog
    - name: create labels
      import_role:
        name: example-cnf-labels
    - name: create app
      import_role:
        name: example-cnf-app
    - name: wait for trex to stablize
      pause:
        seconds: 30
    - name: run migration test
      import_role:
        name: example-cnf-validate
    - name: delete all resource on completion
      import_role:
        name: example-cnf-destroy
      when: not skip_post_delete|bool
    - name: execution results
      debug:
        var: packet_details

