apiVersion: examplecnf.openshift.io/v1
kind: TRexApp
metadata:
  name: trex-app2
  namespace: example-cnf
spec:
  duration: -1
  enableLb: true
  imagePullPolicy: Always
  lbMacs:
  - 40:04:0f:f1:89:01
  - 40:04:0f:f1:89:02
  org: krsacme
  packetRate: 10kpps
  packetSize: 64
  registry: quay.io
  trexApp: false
  trexProfileConfigMap: null
  trexProfileName: null
  version: v0.2.1
