---
- name: create testpmd subscription
  k8s:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: testpmd-operator-subscription
    namespace: "{{ cnf_namespace }}"
    definition:
      spec:
        channel: "{{ testpmd_channel }}"
        name: testpmd-operator
        source: "{{ catalog_name }}"
        sourceNamespace: openshift-marketplace
- name: create trex subscription
  when: enable_trex|bool
  k8s:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: trex-operator-subscription
    namespace: "{{ cnf_namespace }}"
    definition:
      spec:
        channel: "{{ trex_channel }}"
        name: trex-operator
        source: "{{ catalog_name }}"
        sourceNamespace: openshift-marketplace
- name: set csv count
  set_fact:
    csv_count: 2
  when: enable_trex|bool
- name: set csv count for testpmd only
  set_fact:
    csv_count: 1
  when: not enable_trex|bool
- name: "wait for csv installation in {{ cnf_namespace }}"
  k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    namespace: "{{ cnf_namespace }}"
  register: csv_list
  retries: 24
  delay: 5
  until: "csv_list.resources|length >= csv_count"
  failed_when: "csv_list.resources|length < csv_count"
- name: "wait for pod in {{ cnf_namespace }}"
  k8s_info:
    kind: Pod
    namespace: "{{ cnf_namespace }}"
    field_selectors:
      - status.phase=Running
  register: pod_list
  retries: 30
  delay: 5
  until: "pod_list.resources|length >= csv_count"
  failed_when: "pod_list.resources|length < csv_count"
