---
- name: "Installing operator: {{ operator.name }}"
  debug:
    var: operator.name

- name: Create subscription for OLM operator
  community.kubernetes.k8s:
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: "{{ operator.name }}"
        namespace: "{{ operator.namespace }}"
      spec:
        channel: "{{ (operator.channel == '') | ternary(omit, operator.channel) }}"
        config:
          resources: {}
        name: "{{ operator.name }}"
        source: "{{ operator.source }}"
        sourceNamespace: "{{ operator.source_ns }}"

- name: Get operator's package manifest
  community.kubernetes.k8s_info:
    api: packages.operators.coreos.com/v1
    kind: PackageManifest
    name: "{{ operator.name }}"
    namespace: default
  register: packagemanifest
  retries: 9
  delay: 10
  until:
    - packagemanifest.resources | length == 1

- name: "Get operator's default channel name"
  vars:
    channels: "resources[*].status.defaultChannel"
  set_fact:
    default_channel: "{{ packagemanifest | json_query(channels) | join('') | string }}"

- name: "Get operator's CSV for desired channel"
  vars:
    channel: "{{ (operator.channel == '') | ternary(default_channel, operator.channel) }}"
    current_csv: "resources[*].status.channels[? name=='{{ channel }}' ].currentCSV | [0]"
  set_fact:
    operator_csv: "{{ packagemanifest | json_query(current_csv) | first }}"

- name: "Waiting for {{ operator_csv }} CSV to be ready"
  community.kubernetes.k8s_info:
    api: operators.coreos.com/v1alpha1
    namespace: "{{ operator.namespace }}"
    kind: ClusterServiceVersion
    name: "{{ operator_csv }}"
  register: csv
  retries: 20
  delay: 30
  until:
    - csv.resources | length == 1
    - "'status' in csv.resources[0]"
    - "'phase' in csv.resources[0].status"
    - csv.resources[0].status.phase == 'Succeeded' or csv.resources[0].status.phase == 'Present'
