---
- name: create cr for loadbalancer
  k8s:
    definition: "{{ lookup('template', 'lb-cr.yaml.j2') }}"

- name: check loadbalancer pod status to be running
  k8s_info:
    namespace: "{{ cnf_namespace }}"
    kind: Pod
    label_selectors:
      - example-cnf-type=lb-app
  register: lb_pods
  vars:
    container_query: "resources[0].status.containerStatuses[?name=='loadbalancer'].state.running"
    container_status: "{{ lb_pods | json_query(container_query) }}"
  retries: 60
  delay: 5
  until:
    - lb_pods.resources | length == 1
    - lb_pods.resources[0].status.phase == 'Running'
    - container_status | length > 0
