---
- name: create loadbalancer subscription
  k8s:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: lb-operator-subscription
    namespace: "{{ cnf_namespace }}"
    definition:
      spec:
        channel: "{{ testpmd_channel }}"
        name: testpmd-lb-operator
        source: "{{ catalog_name }}"
        sourceNamespace: openshift-marketplace
- name: set loadbalancer csv name
  set_fact:
    lb_csv_name: "testpmd-lb-operator.{{ operator_version }}"
- name: get loadbalancer csv
  k8s_info:
    api: operators.coreos.com/v1alpha1
    namespace: "{{ cnf_namespace }}"
    kind: ClusterServiceVersion
    name: "{{ lb_csv_name }}"
  register: csv
  retries: 30
  delay: 5
  until: "csv.resources|length == 1 and csv.resources[0].status.phase == 'Succeeded'"

- name: create testpmd subscription
  k8s:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: testpmd-operator-subscription
    namespace: "{{ cnf_namespace }}"
    definition:
      spec:
        channel: "{{ testpmd_channel }}"
        name: testpmd-operator
        source: "{{ catalog_name }}"
        sourceNamespace: openshift-marketplace
- name: set testpmd csv name
  set_fact:
    testpmd_csv_name: "testpmd-operator.{{ operator_version }}"
- name: get testpmd csv
  k8s_info:
    api: operators.coreos.com/v1alpha1
    namespace: "{{ cnf_namespace }}"
    kind: ClusterServiceVersion
    name: "{{ testpmd_csv_name }}"
  register: csv
  retries: 30
  delay: 5
  until: "csv.resources|length == 1 and csv.resources[0].status.phase == 'Succeeded'"
  failed_when: "csv.resources|length != 1 or csv.resources[0].status.phase != 'Succeeded'"

- name: create trex subscription
  when: enable_trex|bool
  k8s:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: trex-operator-subscription
    namespace: "{{ cnf_namespace }}"
    definition:
      spec:
        channel: "{{ trex_channel }}"
        name: trex-operator
        source: "{{ catalog_name }}"
        sourceNamespace: openshift-marketplace

- name: trex csv check block
  when: enable_trex|bool
  block:
  - name: set trex csv name
    set_fact:
      trex_csv_name: "trex-operator.{{ operator_version }}"
  - name: get trex csv
    k8s_info:
      api: operators.coreos.com/v1alpha1
      namespace: "{{ cnf_namespace }}"
      kind: ClusterServiceVersion
      name: "{{ trex_csv_name }}"
    register: csv
    retries: 30
    delay: 5
    until: "csv.resources|length == 1 and csv.resources[0].status.phase == 'Succeeded'"
    failed_when: "csv.resources|length != 1 or 'status' not in csv.resources[0] or csv.resources[0].status.phase != 'Succeeded'"
