---
- name: set local fact for trex pod networks
  set_fact:
    networks_trex: []
    packet_gen_net: "{{ packet_generator_networks if enable_lb|bool else cnf_app_networks }}"
# TODO(skramaja): This logic to be improved for multiple
# networks, lets fail it if the length is > 1
- fail:
    msg: "Need to rewrite the mac merging logic"
  when: "packet_gen_net|length != 1"
- name: create network list for trex with hardcoded macs
  set_fact:
    networks_trex: "{{ networks_trex + [ item | combine({ 'mac': trex_mac_list[idx:idx+item.count] }) ] }}"
  loop: "{{ packet_gen_net }}"
  loop_control:
    index_var: idx

- name: create cr for trex
  k8s:
    definition: "{{ lookup('template', 'trex-cr.yaml.j2') }}"
- name: check trex pod count to be 1
  k8s_info:
    namespace: example-cnf
    kind: Pod
    label_selectors:
      - example-cnf-type=pkt-gen
  register: trex_pods
  retries: 60
  delay: 5
  until:
    - trex_pods.resources|length == 1
  failed_when:
    - trex_pods.resources|length != 1
- name: check trex pod status to be running
  k8s_info:
    namespace: example-cnf
    kind: Pod
    label_selectors:
      - example-cnf-type=pkt-gen
  register: trex_pods
  retries: 60
  delay: 5
  until:
    - trex_pods.resources[0].status.phase == 'Running'
  failed_when:
    - trex_pods.resources[0].status.phase != 'Running'
- name: wait for 30 seconds to stabilize trex output
  pause:
    seconds: 30
# Ensure there is atleast one patcket matched event
- name: get packet matched event from trex
  k8s_info:
    namespace: example-cnf
    kind: Event
    field_selectors:
      - reason==PacketMatched
  register: trex_matched_event
  no_log: true
