---
# Customizable variables
cluster_name: cluster5
operator_version: ""
registry_url: "jumphost.{{ cluster_name }}.dfwt5g.lab:5000"
repo_name: nfv-example-cnf

image_pull_policy: Always

catalog_name: nfv-example-cnf-catalog
catalog_image: "{{ registry_url }}/{{ repo_name }}/{{ catalog_name }}:{{ operator_version }}"

cnf_namespace: example-cnf
