---
- name: create namespace
  k8s:
    api_version: v1
    name: "{{ cnf_namespace }}"
    kind: Namespace
- name: create operatorgroup
  k8s:
    api_version: operators.coreos.com/v1
    name: example-cnf-operator-group
    kind: OperatorGroup
    namespace: "{{ cnf_namespace }}"
    definition:
      spec:
        targetNamespaces:
          - "{{ cnf_namespace }}"
